apiVersion: batch/v1
kind: Job
metadata:
  name: fdb-bench
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - foundationdb
                topologyKey: kubernetes.io/hostname

      containers:

      - name: fdb-workloada
        image: pierrezemb/go-ycsb:fdb-6.2.11
        command: [ "/go-ycsb", "run", "basic", "-P", "workloads/workloada", "-p", "fdb.cluster=/mnt/config-volume/cluster-file", "-p", "fdb.apiversion=620"]
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config-volume
      
      - name: fdb-workloadb
        image: pierrezemb/go-ycsb:fdb-6.2.11
        command: [ "/go-ycsb", "run", "basic", "-P", "workloads/workloadb", "-p", "fdb.cluster=/mnt/config-volume/cluster-file", "-p", "fdb.apiversion=620"]
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config-volume

      - name: fdb-workloadc
        image: pierrezemb/go-ycsb:fdb-6.2.11
        command: [ "/go-ycsb", "run", "basic", "-P", "workloads/workloadc", "-p", "fdb.cluster=/mnt/config-volume/cluster-file", "-p", "fdb.apiversion=620"]
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config-volume

      - name: fdb-workloadd
        image: pierrezemb/go-ycsb:fdb-6.2.11
        command: [ "/go-ycsb", "run", "basic", "-P", "workloads/workloadd", "-p", "fdb.cluster=/mnt/config-volume/cluster-file", "-p", "fdb.apiversion=620"]
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config-volume

      - name: fdb-workloade
        image: pierrezemb/go-ycsb:fdb-6.2.11
        command: [ "/go-ycsb", "run", "basic", "-P", "workloads/workloade", "-p", "fdb.cluster=/mnt/config-volume/cluster-file", "-p", "fdb.apiversion=620"]
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config-volume

      - name: fdb-workloadf
        image: pierrezemb/go-ycsb:fdb-6.2.11
        command: [ "/go-ycsb", "run", "basic", "-P", "workloads/workloadf", "-p", "fdb.cluster=/mnt/config-volume/cluster-file", "-p", "fdb.apiversion=620"]
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config-volume

      volumes:
      - name: config-volume
        configMap:
          name: sample-cluster-config
      restartPolicy: Never
  backoffLimit: 1
  completions: 4
  parallelism: 1