apiVersion: batch/v1
kind: Job
metadata:
  name: fdb-bench
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - foundationdb
                topologyKey: kubernetes.io/hostname

      containers:

      - name: fdb-workloada
        image: 231290928314.dkr.ecr.us-east-1.amazonaws.com/fdb-prometheus-exporter:goycsb
        # This is the command i used to spawn lots of threads
        #command: [ "/go-ycsb", "run", "foundationdb", "-P", "workloads/workloada", "-p", "fdb.cluster=/mnt/config-volume/cluster-file", "-p", "fdb.apiversion=620", "-p", "operationcount=1000000", "-p", "insertproportion=1", "-p", "readproportion=0", "-p", "updateproportion=0", "-p", "threadcount=10"]
        command: [ "/go-ycsb", "run", "foundationdb", "-P", "workloads/workloada", "-p", "fdb.cluster=/mnt/config-volume/cluster-file", "-p", "fdb.apiversion=620"]
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config-volume
      
      - name: fdb-workloadb
        image: pierrezemb/go-ycsb:fdb-6.2.11
        command: [ "/go-ycsb", "run", "foundationdb", "-P", "workloads/workloadb", "-p", "fdb.cluster=/mnt/config-volume/cluster-file", "-p", "fdb.apiversion=620"]
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config-volume

      - name: fdb-workloadc
        image: pierrezemb/go-ycsb:fdb-6.2.11
        command: [ "/go-ycsb", "run", "foundationdb", "-P", "workloads/workloadc", "-p", "fdb.cluster=/mnt/config-volume/cluster-file", "-p", "fdb.apiversion=620"]
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config-volume

      - name: fdb-workloadd
        image: pierrezemb/go-ycsb:fdb-6.2.11
        command: [ "/go-ycsb", "run", "foundationdb", "-P", "workloads/workloadd", "-p", "fdb.cluster=/mnt/config-volume/cluster-file", "-p", "fdb.apiversion=620"]
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config-volume

      - name: fdb-workloade
        image: pierrezemb/go-ycsb:fdb-6.2.11
        command: [ "/go-ycsb", "run", "foundationdb", "-P", "workloads/workloade", "-p", "fdb.cluster=/mnt/config-volume/cluster-file", "-p", "fdb.apiversion=620"]
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config-volume

      - name: fdb-workloadf
        image: pierrezemb/go-ycsb:fdb-6.2.11
        command: [ "/go-ycsb", "run", "foundationdb", "-P", "workloads/workloadf", "-p", "fdb.cluster=/mnt/config-volume/cluster-file", "-p", "fdb.apiversion=620"]
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config-volume

      volumes:
      - name: config-volume
        configMap:
          name: sample-cluster-config
      restartPolicy: Never
  backoffLimit: 1
  completions: 4
  parallelism: 1