{
 "title": "FDB",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(fdb_generation{}, app_kubernetes_io_namespace)"
    }
   },
   {
    "name": "release_name",
    "query": {
     "query": "label_values(fdb_generation{app_kubernetes_io_namespace=\"$namespace\"}, app_kubernetes_io_name)"
    }
   },
   { "name": "fdb_class", "query": "log,storage,stateless" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Role count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "fdb_database_configuration{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "fdb_database_status{app_kubernetes_io_name=\"$release_name\", app_kubernetes_io_namespace=\"$namespace\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "fdb_coordinators_reachable{app_kubernetes_io_name=\"$release_name\", app_kubernetes_io_namespace=\"$namespace\"}",
     "legendFormat": "{{app_kubernetes_io_namespace}} - {{address}}"
    }
   ]
  },
  {
   "title": "FDB generation bump",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "increase(fdb_generation{app_kubernetes_io_name=\"$release_name\", app_kubernetes_io_namespace=\"$namespace\"}[1d])",
     "legendFormat": "generation"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "timeseries",
   "description": "FDB Connected Clients",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "fdb_connected_clients{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"}",
     "legendFormat": "clients-{{app_kubernetes_io_namespace}}"
    }
   ]
  },
  {
   "title": "Operations/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(fdb_workload_operations_total{app_kubernetes_io_name=\"$release_name\", app_kubernetes_io_namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{app_kubernetes_io_namespace}} - {{ operation }} "
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(fdb_workload_transactions_total{app_kubernetes_io_name=\"$release_name\", app_kubernetes_io_namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Latency Probe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "fdb_workload_latency_probe{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"}",
     "legendFormat": "{{app_kubernetes_io_namespace}} latency  {{operation}}"
    }
   ]
  },
  {
   "title": "Qos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transactions Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "fdb_qos_transactions_per_second_limit{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"}",
     "legendFormat": "{{app_kubernetes_io_namespace}} - {{kind}}"
    }
   ]
  },
  {
   "title": "Qos Limit Reason",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(fdb_qos_performance_limited_by{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"}) by(app_kubernetes_io_name)",
     "legendFormat": "{{app_kubernetes_io_namespace}}"
    }
   ]
  },
  {
   "title": "Storage Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "fdb_processes_storage_read_latency{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"}",
     "legendFormat": "{{app_kubernetes_io_namespace}} - {{address}} - {{percentile}}"
    }
   ]
  },
  {
   "title": "Work Queue Bytes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "fdb_qos_worst_queue_bytes{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "FDB Data Movement",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "fdb_data_move{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(fdb_processes_disk_reads_total{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"}[1m])) by(address)",
       "legendFormat": "{{address}}"
      }
     ]
    },
    {
     "title": "Disk write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(fdb_processes_disk_writes_total{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"}[5m])) by(address)",
       "legendFormat": "{{ address }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory usage relative",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(fdb_processes_memory_used_bytes{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"}) by(address,role) / sum(fdb_processes_memory_available_bytes{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"}) by(address,role)",
       "legendFormat": "{{ address }}"
      }
     ]
    },
    {
     "title": "Memory usage absolute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(fdb_processes_memory_used_bytes{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"}) by(address)",
       "legendFormat": "{{address}}"
      }
     ]
    }
   ]
  },
  {
   "title": "KV store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Absolute KV used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fdb_processes_kvstore_used_bytes{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"} > 0",
       "legendFormat": "{{ address }}"
      }
     ]
    },
    {
     "title": "Relative KV used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(fdb_processes_kvstore_used_bytes{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"} / fdb_processes_kvstore_total_bytes{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"}) > 0",
       "legendFormat": "{{ address }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Absolute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "fdb_processes_queue_disk_used_bytes{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"} > 0",
     "legendFormat": "{{ address }} | {{ role }}"
    }
   ]
  },
  {
   "title": "Relative",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "fdb_processes_queue_disk_used_bytes{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"} / fdb_processes_queue_disk_total_bytes{app_kubernetes_io_name=\"$release_name\",app_kubernetes_io_namespace=\"$namespace\"}",
     "legendFormat": "{{ address }} | {{ role }}"
    }
   ]
  },
  {
   "title": "Pod class $fdb_class",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "repeat": "fdb_class",
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\"$release_name-$fdb_class.*\",container=\"foundationdb\"})",
     "legendFormat": "request"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\"$release_name-$fdb_class.*\", container=\"foundationdb\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "max(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$release_name-$fdb_class.*\", container=\"foundationdb\"}) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 65 },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\"$release_name-$fdb_class.*\", container=\"foundationdb\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\"$release_name-$fdb_class.*\",container=\"foundationdb\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "max(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$release_name-$fdb_class.*\", container=\"foundationdb\"}[5m])) by (pod)) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "RT Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$release_name-$fdb_class.*\"}[$__rate_interval])) by (pod) + sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$release_name-$fdb_class.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "IOPS R+W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{container!=\"\",namespace=\"$namespace\", pod=~\"$release_name-$fdb_class.*\"}[$__rate_interval]) + rate(container_fs_writes_total{container!=\"\",namespace=\"$namespace\", pod=~\"$release_name-$fdb_class.*\"}[$__rate_interval])))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "IO Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", namespace=\"$namespace\", pod=~\"$release_name-$fdb_class.*\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{container!=\"\",namespace=\"$namespace\", pod=~\"$release_name-$fdb_class.*\"}[$__rate_interval]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\",persistentvolumeclaim=~\"$release_name-$fdb_class.*\"} - kubelet_volume_stats_available_bytes{namespace=\"$namespace\",persistentvolumeclaim=~\"$release_name-$fdb_class.*\"})",
     "legendFormat": "{{ persistentvolumeclaim }}"
    },
    {
     "expr": "avg(kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\",persistentvolumeclaim=~\"$release_name-$fdb_class.*\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Disk busy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "fdb_processes_disk_busy{namespace=\"$namespace\",classtype=~\"$fdb_class\"}",
     "legendFormat": "{{address}} - {{machine_id}}"
    }
   ]
  }
 ]
}